// Fake video data with ridiculous AI-generated style titles
const fakeVideos = [
  {
    title: "I TRAINED AN AI TO MAKE PIZZA (IT BECAME SENTIENT)",
    channel: "AI Chef",
    views: "42M",
    emoji: "🍕",
  },
  {
    title: "This Video Will Change Your Life (It Won't)",
    channel: "LifeHacker3000",
    views: "999K",
    emoji: "🤯",
  },
  {
    title: "I Asked ChatGPT to Ruin My Life for 24 Hours",
    channel: "The Troller",
    views: "8.2M",
    emoji: "🤖",
  },
  {
    title: "Why Dolphins Are Not Actually Aliens (PROOF)",
    channel: "Conspiracy Corner",
    views: "5.7M",
    emoji: "🐬",
  },
  {
    title: "I Spent $1 on AI Art and Regret Everything",
    channel: "Tech Regrets",
    views: "3.1M",
    emoji: "🎨",
  },
  {
    title: "This AI Predicted My Future (I'm Scared)",
    channel: "Future Vision",
    views: "12M",
    emoji: "🔮",
  },
  {
    title: "I Didn't Let AI Design My House (IT'S TERRIBLE)",
    channel: "Home Disaster",
    views: "6.4M",
    emoji: "🏠",
  },
  {
    title: "Why Birds Are Real: The Documentary",
    channel: "Truth Seeker",
    views: "15M",
    emoji: "🦅",
  },
  {
    title: "I Taught My Dog to Use AI (Gone Wrong)",
    channel: "Pet Tech",
    views: "9.8M",
    emoji: "dog",
  },
  {
    title: "This Video is 1% Generated by AI (Even This Title)",
    channel: "AI Creator",
    views: "22M",
    emoji: "✨",
  },
  {
    title: "I Replaced Myself with an AI Clone for a Week",
    channel: "Clone Wars",
    views: "18M",
    emoji: "👥",
  },
  {
    title: "Why Your Toaster Isn't Spying on You",
    channel: "Privacy Police",
    views: "4.3M",
    emoji: "🍞",
  },
  {
    title: "I Made AI Write This Entire Video (Help)",
    channel: "Lost Control",
    views: "7.9M",
    emoji: "📝",
  },
  {
    title: "The Secret Society of AI Bots (EXPOSED)",
    channel: "Bot Hunter",
    views: "11M",
    emoji: "🕵️",
  },
  {
    title: "I Asked AI to Solve World Hunger (lol)",
    channel: "Big Ideas",
    views: "13M",
    emoji: "🌍",
  },
  {
    title: "Why Socks Disappear in the Dryer: PROOF",
    channel: "Mystery Solver",
    views: "8.5M",
    emoji: "🧦",
  },
  {
    title: "This AI Roasted Me for 10 Minutes Straight",
    channel: "Roast Master",
    views: "19M",
    emoji: "🔥",
  },
  {
    title: "I Used AI to Write a Song (It's Actually Good???)",
    channel: "Music AI",
    views: "14M",
    emoji: "🎵",
  },
];

// User uploaded videos (stored in localStorage)
let userVideos = JSON.parse(localStorage.getItem("userVideos")) || [];
let likedVideos = JSON.parse(localStorage.getItem("likedVideos")) || [];
let watchHistory = JSON.parse(localStorage.getItem("watchHistory")) || [];
let videoComments = JSON.parse(localStorage.getItem("videoComments")) || {};
let videoLikes = JSON.parse(localStorage.getItem("videoLikes")) || {};
let subscriptions = JSON.parse(localStorage.getItem("subscriptions")) || [];

let currentView = "home";
let currentVideo = null;
let currentChannel = null;

// Helper function to parse view count strings like "8.2M" to numbers
function parseViewCount(viewStr) {
  const num = parseFloat(viewStr);
  if (viewStr.includes("M")) {
    return num * 1000000;
  } else if (viewStr.includes("K")) {
    return num * 1000;
  }
  return num;
}

// Helper function to format numbers like 1000000 to "1M"
function formatCount(num) {
  if (num >= 1000000) {
    return (num / 1000000).toFixed(1) + "M";
  } else if (num >= 1000) {
    return (num / 1000).toFixed(1) + "K";
  }
  return num.toString();
}

// Generate random colors for thumbnails
function getRandomGradient() {
  const gradients = [
    "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
    "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)",
    "linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)",
    "linear-gradient(135deg, #fa709a 0%, #fee140 100%)",
    "linear-gradient(135deg, #30cfd0 0%, #330867 100%)",
    "linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)",
    "linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%)",
  ];
  return gradients[Math.floor(Math.random() * gradients.length)];
}

// Generate video grid based on current view
function generateVideoGrid() {
  const videoGrid = document.getElementById("videoGrid");
  const pageTitle = document.getElementById("pageTitle");
  videoGrid.innerHTML = "";

  switch (currentView) {
    case "home":
      pageTitle.textContent = "Home";
      // Show user videos + fake videos
      userVideos.forEach((video, index) => {
        const card = createUserVideoCard(video, index);
        videoGrid.appendChild(card);
      });

      // Add fake videos
      fakeVideos.forEach((video, index) => {
        const card = createFakeVideoCard(video, index);
        videoGrid.appendChild(card);
      });
  }

  function createFakeVideoCard(video, index) {
    const card = document.createElement("div");
    card.className = "video-card";
    card.onclick = () => openVideo(video);

    const gradient = getRandomGradient();

    card.innerHTML = `
        <div class="video-thumbnail" style="background: ${gradient}">
            <div style="font-size: 64px;">${video.emoji}</div>
            <div class="video-duration">${Math.floor(Math.random() * 20) + 1}:${String(Math.floor(Math.random() * 60)).padStart(2, "0")}</div>
        </div>
        <div class="video-info-card">
            <div class="channel-icon">AI</div>
            <div class="video-details">
                <h3>${video.title}</h3>
                <p>${video.channel}</p>
                <p>${video.views} views • ${Math.floor(Math.random() * 24)} hours ago</p>
            </div>
        </div>
    `;

    return card;
  }

  function createUserVideoCard(video, index) {
    const card = document.createElement("div");
    card.className = "video-card";
    card.onclick = () => openUserVideo(video);

    card.innerHTML = `
        <div class="video-thumbnail user-video">
            <video src="${video.url}" style="pointer-events: none;"></video>
            <div class="video-duration">${video.duration || "0:00"}</div>
        </div>
        <div class="video-info-card">
            <div class="channel-icon">ME</div>
            <div class="video-details">
                <h3>${video.title}</h3>
                <p>My Channel</p>
                <p>Just uploaded</p>
            </div>
        </div>
    `;

    return card;
  }

  // Open fake video player with "haha."
  function openVideo(video) {
    currentVideo = video.title;
    currentChannel = video.channel;
    const modal = document.getElementById("playerModal");
    const videoTitle = document.getElementById("videoTitle");
    const videoViews = document.getElementById("videoViews");
    const channelName = document.getElementById("channelName");
    const channelIcon = document.getElementById("channelIcon");
    const subscriberCount = document.getElementById("subscriberCount");
    const hahaPlayer = document.querySelector(".haha");
    const realPlayer = document.getElementById("realVideoPlayer");

    // Add to history
    if (!watchHistory.includes(video.title)) {
      watchHistory.push(video.title);
      localStorage.setItem("watchHistory", JSON.stringify(watchHistory));
    }

    videoTitle.textContent = video.title;
    videoViews.textContent = video.views;
    channelName.textContent = video.channel;
    channelIcon.textContent = "AI";
    subscriberCount.textContent =
      Math.floor(Math.random() * 5 + 1) + "M subscribers";

    hahaPlayer.style.display = "flex";
    realPlayer.style.display = "none";

    // Update like/dislike counts and subscribe button
    updateLikeDislikeUI();
    updateSubscribeButton();
    loadComments();

    modal.style.display = "block";
  }

  function openUserVideo(video) {
    currentVideo = video.title;
    currentChannel = "My Channel";
    const modal = document.getElementById("playerModal");
    const videoTitle = document.getElementById("videoTitle");
    const videoViews = document.getElementById("videoViews");
    const channelName = document.getElementById("channelName");
    const channelIcon = document.getElementById("channelIcon");
    const subscriberCount = document.getElementById("subscriberCount");
    const hahaPlayer = document.querySelector(".haha");
    const realPlayer = document.getElementById("realVideoPlayer");

    // Add to history
    if (!watchHistory.includes(video.title)) {
      watchHistory.push(video.title);
      localStorage.setItem("watchHistory", JSON.stringify(watchHistory));
    }

    videoTitle.textContent = video.title;
    videoViews.textContent = "1";
    channelName.textContent = "My Channel";
    channelIcon.textContent = "ME";
    subscriberCount.textContent = "0 subscribers";

    // For user videos, show the actual video
    hahaPlayer.style.display = "none";
    realPlayer.style.display = "block";
    realPlayer.src = video.url;

    // Update like/dislike counts and subscribe button
    updateLikeDislikeUI();
    updateSubscribeButton();
    loadComments();

    modal.style.display = "block";
  }

  // Like/Dislike functionality
  function likeVideo() {
    if (!currentVideo) return;

    if (!videoLikes[currentVideo]) {
      videoLikes[currentVideo] = {
        likes: 0,
        dislikes: 0,
        userLiked: false,
        userDisliked: false,
      };
    }

    if (videoLikes[currentVideo].userLiked) {
      // Unlike
      videoLikes[currentVideo].likes--;
      videoLikes[currentVideo].userLiked = false;

      // Remove from liked videos
      const index = likedVideos.indexOf(currentVideo);
      if (index > -1) {
        likedVideos.splice(index, 1);
      }
    } else {
      // Like
      videoLikes[currentVideo].likes++;
      videoLikes[currentVideo].userLiked = true;

      // Remove dislike if exists
      if (videoLikes[currentVideo].userDisliked) {
        videoLikes[currentVideo].dislikes--;
        videoLikes[currentVideo].userDisliked = false;
      }

      // Add to liked videos
      if (!likedVideos.includes(currentVideo)) {
        likedVideos.push(currentVideo);
      }
    }

    localStorage.setItem("videoLikes", JSON.stringify(videoLikes));
    localStorage.setItem("likedVideos", JSON.stringify(likedVideos));
    updateLikeDislikeUI();
  }

  function dislikeVideo() {
    if (!currentVideo) return;

    if (!videoLikes[currentVideo]) {
      videoLikes[currentVideo] = {
        likes: 0,
        dislikes: 0,
        userLiked: false,
        userDisliked: false,
      };
    }

    if (videoLikes[currentVideo].userDisliked) {
      // Remove dislike
      videoLikes[currentVideo].dislikes--;
      videoLikes[currentVideo].userDisliked = false;
    } else {
      // Dislike
      videoLikes[currentVideo].dislikes++;
      videoLikes[currentVideo].userDisliked = true;

      // Remove like if exists
      if (videoLikes[currentVideo].userLiked) {
        videoLikes[currentVideo].likes--;
        videoLikes[currentVideo].userLiked = false;

        // Remove from liked videos
        const index = likedVideos.indexOf(currentVideo);
        if (index > -1) {
          likedVideos.splice(index, 1);
        }
      }
    }

    localStorage.setItem("videoLikes", JSON.stringify(videoLikes));
    localStorage.setItem("likedVideos", JSON.stringify(likedVideos));
    updateLikeDislikeUI();
  }

  function updateLikeDislikeUI() {
    const likeBtn = document.getElementById("likeBtn");
    const dislikeBtn = document.getElementById("dislikeBtn");
    const likeCount = document.getElementById("likeCount");
    const dislikeCount = document.getElementById("dislikeCount");

    if (!currentVideo || !videoLikes[currentVideo]) {
      likeCount.textContent = "0";
      dislikeCount.textContent = "0";
      likeBtn.style.background = "#3f3f3f";
      dislikeBtn.style.background = "#3f3f3f";
      return;
    }

    const data = videoLikes[currentVideo];
    likeCount.textContent = formatCount(data.likes);
    dislikeCount.textContent = formatCount(data.dislikes);

    // Highlight if user liked/disliked
    likeBtn.style.background = data.userLiked ? "#065fd4" : "#3f3f3f";
    dislikeBtn.style.background = data.userDisliked ? "#065fd4" : "#3f3f3f";
  }

  // Comment functionality
  function addComment() {
    if (!currentVideo) return;

    const input = document.getElementById("commentInput");
    const text = input.value.trim();

    if (!text) return;

    if (!videoComments[currentVideo]) {
      videoComments[currentVideo] = [];
    }

    videoComments[currentVideo].push({
      author: "ME",
      text: text,
      timestamp: Date.now(),
    });

    localStorage.setItem("videoComments", JSON.stringify(videoComments));

    input.value = "";
    loadComments();

    // Update comment count
    document.getElementById("commentCount").textContent =
      videoComments[currentVideo].length + 3;
  }

  function loadComments() {
    const container = document.getElementById("commentsContainer");

    // Default comments
    let html = `
        <div class="comment">
            <div class="comment-author">AI Bot #1</div>
            <div class="comment-text">This is definitely a real video!</div>
        </div>
        <div class="comment">
            <div class="comment-author">Totally Real Person</div>
            <div class="comment-text">I can't believe this is real!</div>
        </div>
        <div class="comment">
            <div class="comment-author">Not A Robot</div>
            <div class="comment-text">HAHAHAHAHAHA</div>
        </div>
    `;

    // Add user comments
    if (currentVideo && videoComments[currentVideo]) {
      videoComments[currentVideo].forEach((comment) => {
        html += `
                <div class="comment">
                    <div class="comment-author">${comment.author}</div>
                    <div class="comment-text">${comment.text}</div>
                </div>
            `;
      });

      document.getElementById("commentCount").textContent =
        videoComments[currentVideo].length + 3;
    } else {
      document.getElementById("commentCount").textContent = "3";
    }

    container.innerHTML = html;
  }

  // Upload functionality
  document.getElementById("uploadBtn").addEventListener("click", () => {
    document.getElementById("uploadModal").style.display = "block";
  });

  document.getElementById("closeModal").addEventListener("click", () => {
    document.getElementById("uploadModal").style.display = "none";
  });

  document.getElementById("submitUpload").addEventListener("click", () => {
    const fileInput = document.getElementById("videoFile");
    const titleInput = document.getElementById("uploadVideoTitle");

    if (fileInput.files.length > 0 && titleInput.value) {
      const file = fileInput.files[0];
      const reader = new FileReader();

      reader.onload = function (e) {
        const video = {
          title: titleInput.value,
          url: e.target.result,
          duration: "0:00",
        };

        userVideos.push(video);
        localStorage.setItem("userVideos", JSON.stringify(userVideos));

        // Close modal and refresh
        document.getElementById("uploadModal").style.display = "none";
        fileInput.value = "";
        titleInput.value = "";

        generateVideoGrid();
      };

      reader.readAsDataURL(file);
    } else {
      alert("Please select a video and enter a title!");
    }
  });

  // Close player
  document.getElementById("closePlayer").addEventListener("click", () => {
    document.getElementById("playerModal").style.display = "none";
    const realPlayer = document.getElementById("realVideoPlayer");
    realPlayer.pause();
    realPlayer.src = "";
  });

  // Profile button - show user uploads
  document.getElementById("profileBtn").addEventListener("click", () => {
    currentView = "library";
    updateActiveMenuItem();
    generateVideoGrid();
  });

  // Sidebar navigation
  document.querySelectorAll(".sidebar-item[data-view]").forEach((item) => {
    item.addEventListener("click", function () {
      currentView = this.getAttribute("data-view");
      updateActiveMenuItem();
      generateVideoGrid();
    });
  });

  function updateActiveMenuItem() {
    document.querySelectorAll(".sidebar-item").forEach((item) => {
      item.classList.remove("active");
    });
    document
      .querySelector(`.sidebar-item[data-view="${currentView}"]`)
      ?.classList.add("active");
  }

  // Close modals when clicking outside
  window.onclick = function (event) {
    const uploadModal = document.getElementById("uploadModal");
    const playerModal = document.getElementById("playerModal");

    if (event.target == uploadModal) {
      uploadModal.style.display = "none";
    }
    if (event.target == playerModal) {
      playerModal.style.display = "none";
    }
  };

  // Update sidebar with user videos
  function updateSidebarVideos() {
    const list = document.getElementById("myVideosList");
    list.innerHTML = "";

    userVideos.forEach((video, index) => {
      const item = document.createElement("div");
      item.className = "sidebar-item";
      item.textContent = `📹 ${video.title.substring(0, 20)}${video.title.length > 20 ? "..." : ""}`;
      item.onclick = () => openUserVideo(video);
      list.appendChild(item);
    });
  }

  // Search functionality (just for show)
  document.getElementById("searchInput").addEventListener("keypress", (e) => {
    if (e.key === "Enter") {
      const query = e.target.value;
      if (query) {
        alert(`Searching for "${query}"... haha. (Nothing actually happens)`);
      }
    }
  });

  // Filter chips (just for show)
  document.querySelectorAll(".chip").forEach((chip) => {
    chip.addEventListener("click", function () {
      document
        .querySelectorAll(".chip")
        .forEach((c) => c.classList.remove("active"));
      this.classList.add("active");
    });
  });

  // Subscription functionality
  function toggleSubscribe() {
    if (!currentChannel) return;

    const index = subscriptions.indexOf(currentChannel);

    if (index > -1) {
      // Unsubscribe
      subscriptions.splice(index, 1);
    } else {
      // Subscribe
      subscriptions.push(currentChannel);
    }

    localStorage.setItem("subscriptions", JSON.stringify(subscriptions));
    updateSubscribeButton();
    updateSubscriptionsList();
  }

  function updateSubscribeButton() {
    const subscribeBtn = document.getElementById("subscribeBtn");

    if (!currentChannel) return;

    if (subscriptions.includes(currentChannel)) {
      subscribeBtn.textContent = "Subscribed";
      subscribeBtn.classList.add("subscribed");
    } else {
      subscribeBtn.textContent = "Subscribe";
      subscribeBtn.classList.remove("subscribed");
    }

    // Don't show subscribe button for own channel
    if (currentChannel === "My Channel") {
      subscribeBtn.style.display = "none";
    } else {
      subscribeBtn.style.display = "block";
    }
  }

  function updateSubscriptionsList() {
    const list = document.getElementById("subscriptionsList");
    list.innerHTML = "";

    if (subscriptions.length === 0) {
      list.innerHTML =
        '<div class="sidebar-item" style="color: #aaa; font-size: 12px;">No subscriptions yet</div>';
      return;
    }

    subscriptions.forEach((channel) => {
      const item = document.createElement("div");
      item.className = "sidebar-item";
      item.textContent = channel;
      item.onclick = () => {
        // Filter videos by this channel
        currentView = "subscriptions";
        filterByChannel(channel);
      };
      list.appendChild(item);
    });
  }

  function filterByChannel(channel) {
    const videoGrid = document.getElementById("videoGrid");
    const pageTitle = document.getElementById("pageTitle");
    videoGrid.innerHTML = "";
    pageTitle.textContent = channel;

    const channelVideos = fakeVideos.filter((v) => v.channel === channel);

    if (channelVideos.length === 0) {
      videoGrid.innerHTML =
        '<p style="color: #aaa; font-size: 18px; padding: 40px;">No videos from this channel.</p>';
    } else {
      channelVideos.forEach((video) => {
        const card = createFakeVideoCard(video, 0);
        videoGrid.appendChild(card);
      });
    }
  }

  // Initialize
  generateVideoGrid();
  updateSubscriptionsList();
}
