// Fake video data with ridiculous AI-generated style titles
const fakeVideos = [
    { title: "I TRAINED AN AI TO MAKE PIZZA (IT BECAME SENTIENT)", channel: "AI Chef", views: "42M", emoji: "🍕" },
    { title: "This Video Will Change Your Life (It Won't)", channel: "LifeHacker3000", views: "999K", emoji: "🤯" },
    { title: "I Asked ChatGPT to Run My Life for 24 Hours", channel: "AI Experiments", views: "8.2M", emoji: "🤖" },
    { title: "Why Dolphins Are Actually Aliens (PROOF)", channel: "Conspiracy Corner", views: "5.7M", emoji: "🐬" },
    { title: "I Spent $10,000 on AI Art and Regret Everything", channel: "Tech Regrets", views: "3.1M", emoji: "🎨" },
    { title: "This AI Predicted My Future (I'm Scared)", channel: "Future Vision", views: "12M", emoji: "🔮" },
    { title: "I Let AI Design My House (IT'S TERRIBLE)", channel: "Home Disaster", views: "6.4M", emoji: "🏠" },
    { title: "Why Birds Aren't Real: The Documentary", channel: "Truth Seeker", views: "15M", emoji: "🦅" },
    { title: "I Taught My Dog to Use AI (Gone Wrong)", channel: "Pet Tech", views: "9.8M", emoji: "🐕" },
    { title: "This Video is 100% Generated by AI (Even This Title)", channel: "AI Creator", views: "22M", emoji: "✨" },
    { title: "I Replaced Myself with an AI Clone for a Week", channel: "Clone Wars", views: "18M", emoji: "👥" },
    { title: "Why Your Toaster is Spying on You", channel: "Privacy Police", views: "4.3M", emoji: "🍞" },
    { title: "I Made AI Write This Entire Video (Help)", channel: "Lost Control", views: "7.9M", emoji: "📝" },
    { title: "The Secret Society of AI Bots (EXPOSED)", channel: "Bot Hunter", views: "11M", emoji: "🕵️" },
    { title: "I Asked AI to Solve World Hunger (lol)", channel: "Big Ideas", views: "13M", emoji: "🌍" },
    { title: "Why Socks Disappear in the Dryer: PROOF", channel: "Mystery Solver", views: "8.5M", emoji: "🧦" },
    { title: "This AI Roasted Me for 10 Minutes Straight", channel: "Roast Master", views: "19M", emoji: "🔥" },
    { title: "I Used AI to Write a Song (It's Actually Good???)", channel: "Music AI", views: "14M", emoji: "🎵" },
];

// User uploaded videos (stored in localStorage)
let userVideos = JSON.parse(localStorage.getItem('userVideos')) || [];

// Generate random colors for thumbnails
function getRandomGradient() {
    const gradients = [
        'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
        'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
        'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
        'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
        'linear-gradient(135deg, #30cfd0 0%, #330867 100%)',
        'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)',
        'linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%)',
    ];
    return gradients[Math.floor(Math.random() * gradients.length)];
}

// Generate fake video cards
function generateVideoGrid() {
    const videoGrid = document.getElementById('videoGrid');
    videoGrid.innerHTML = '';

    // Add user videos first
    userVideos.forEach((video, index) => {
        const card = createUserVideoCard(video, index);
        videoGrid.appendChild(card);
    });

    // Add fake videos
    fakeVideos.forEach((video, index) => {
        const card = createFakeVideoCard(video, index);
        videoGrid.appendChild(card);
    });
}

function createFakeVideoCard(video, index) {
    const card = document.createElement('div');
    card.className = 'video-card';
    card.onclick = () => openVideo(video);

    const gradient = getRandomGradient();

    card.innerHTML = `
        <div class="video-thumbnail" style="background: ${gradient}">
            <div style="font-size: 64px;">${video.emoji}</div>
            <div class="video-duration">${Math.floor(Math.random() * 20) + 1}:${String(Math.floor(Math.random() * 60)).padStart(2, '0')}</div>
        </div>
        <div class="video-info-card">
            <div class="channel-icon">AI</div>
            <div class="video-details">
                <h3>${video.title}</h3>
                <p>${video.channel}</p>
                <p>${video.views} views • ${Math.floor(Math.random() * 24)} hours ago</p>
            </div>
        </div>
    `;

    return card;
}

function createUserVideoCard(video, index) {
    const card = document.createElement('div');
    card.className = 'video-card';
    card.onclick = () => openUserVideo(video);

    card.innerHTML = `
        <div class="video-thumbnail user-video">
            <video src="${video.url}" style="pointer-events: none;"></video>
            <div class="video-duration">${video.duration || '0:00'}</div>
        </div>
        <div class="video-info-card">
            <div class="channel-icon">ME</div>
            <div class="video-details">
                <h3>${video.title}</h3>
                <p>My Channel</p>
                <p>Just uploaded</p>
            </div>
        </div>
    `;

    return card;
}

// Open video player with "haha."
function openVideo(video) {
    const modal = document.getElementById('playerModal');
    const videoTitle = document.getElementById('videoTitle');
    const videoViews = document.getElementById('videoViews');

    videoTitle.textContent = video.title;
    videoViews.textContent = video.views;

    modal.style.display = 'block';
}

function openUserVideo(video) {
    // Even user videos just show "haha." :)
    const modal = document.getElementById('playerModal');
    const videoTitle = document.getElementById('videoTitle');
    const videoViews = document.getElementById('videoViews');

    videoTitle.textContent = video.title;
    videoViews.textContent = '0';

    modal.style.display = 'block';
}

// Upload functionality
document.getElementById('uploadBtn').addEventListener('click', () => {
    document.getElementById('uploadModal').style.display = 'block';
});

document.getElementById('closeModal').addEventListener('click', () => {
    document.getElementById('uploadModal').style.display = 'none';
});

document.getElementById('submitUpload').addEventListener('click', () => {
    const fileInput = document.getElementById('videoFile');
    const titleInput = document.getElementById('videoTitle');

    if (fileInput.files.length > 0 && titleInput.value) {
        const file = fileInput.files[0];
        const reader = new FileReader();

        reader.onload = function(e) {
            const video = {
                title: titleInput.value,
                url: e.target.result,
                duration: '0:00'
            };

            userVideos.push(video);
            localStorage.setItem('userVideos', JSON.stringify(userVideos));

            // Close modal and refresh
            document.getElementById('uploadModal').style.display = 'none';
            fileInput.value = '';
            titleInput.value = '';

            generateVideoGrid();
            updateSidebarVideos();
        };

        reader.readAsDataURL(file);
    } else {
        alert('Please select a video and enter a title!');
    }
});

// Close player
document.getElementById('closePlayer').addEventListener('click', () => {
    document.getElementById('playerModal').style.display = 'none';
});

// Close modals when clicking outside
window.onclick = function(event) {
    const uploadModal = document.getElementById('uploadModal');
    const playerModal = document.getElementById('playerModal');

    if (event.target == uploadModal) {
        uploadModal.style.display = 'none';
    }
    if (event.target == playerModal) {
        playerModal.style.display = 'none';
    }
}

// Update sidebar with user videos
function updateSidebarVideos() {
    const list = document.getElementById('myVideosList');
    list.innerHTML = '';

    userVideos.forEach((video, index) => {
        const item = document.createElement('div');
        item.className = 'sidebar-item';
        item.textContent = `📹 ${video.title.substring(0, 20)}${video.title.length > 20 ? '...' : ''}`;
        item.onclick = () => openUserVideo(video);
        list.appendChild(item);
    });
}

// Search functionality (just for show)
document.getElementById('searchInput').addEventListener('keypress', (e) => {
    if (e.key === 'Enter') {
        const query = e.target.value;
        if (query) {
            alert(`Searching for "${query}"... haha. (Nothing actually happens)`);
        }
    }
});

// Filter chips (just for show)
document.querySelectorAll('.chip').forEach(chip => {
    chip.addEventListener('click', function() {
        document.querySelectorAll('.chip').forEach(c => c.classList.remove('active'));
        this.classList.add('active');
    });
});

// Initialize
generateVideoGrid();
updateSidebarVideos();
